# Generated by Django 4.0.1 on 2024-08-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
